security:
    providers:
        our_db_provider:
            entity:
                class: App\Entity\Participants
                property: mail
    firewalls:
        main:
            pattern: ^/
            provider: our_db_provider
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path: logout
                target: login

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 600 # 10 min
                path: /
    encoders:
        App\Entity\Participants:
            algorithm: bcrypt
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
